# workflow name
name: Deploy To Github And Coding

# master branch on push, auto run
on: [push, repository_dispatch]

# YUQUE_TOKEN
# Github_API_Token
# Coding_API_Token
# Coding_API_Username
jobs:
  deploy: 
    name: Deploy Hexo Public To Pages
    runs-on: ubuntu-latest 
    env:
      TZ: Asia/Shanghai    
        
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout Repository master branch
      uses: actions/checkout@master 
      
    # from: https://github.com/actions/setup-node  
    - name: Setup Node.js 10.x 
      uses: actions/setup-node@master
      with:
        node-version: "10.x"
    
    - name: Setup Git Infomation
      run: | 
        git config --global user.name 'hongweifuture' 
        git config --global user.email 'hongweifuture@163.com'  
 
    - name: Get Latest Commit Message 
      run: |
        git log --pretty=format:"%s from Github Actions at `date +"%Y-%m-%d %H:%M:%S"`" --date=short -n 1  > commit-message.log
        
    - name: Setup Hexo Dependencies and Generate public files
      env:
        YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
      run: |
        npm install hexo-cli -g
        npm install yuque-hexo -g
        npm install
        npm run start
        
    - name: Deploy To Github Pages 
      env:
        Github_Pages: github.com/hongweifuture/hongweifuture.github.io
        Github_Token: ${{ secrets.Github_API_Token }}
      run: |  
        git clone https://${Github_Pages} .github_pages
        cd .github_pages
        git checkout master
        cd ../
        mv .github_pages/.git/ ./public/
        mv ./README.md ./public/
        cd ./public/
        git add .
        git commit -F ../commit-message.log
        git push --force --quiet "https://${Github_Token}@${Github_Pages}" master:master

    - name: Deploy To Coding Pages 
      env:
        Coding_Pages: e.coding.net/hongweifuture/hongweifuture.coding.me.git
        Coding_Token: ${{ secrets.Coding_API_Token }}
        Coding_Username: ${{ secrets.Coding_API_Username }}
      run: |
        git clone https://${Coding_Username}:${Coding_Token}@${Coding_Pages} .coding_pages
        cd .coding_pages
        git checkout master
        cd ../
        rm -r ./public/.git/
        mv .coding_pages/.git/ ./public/
        cd ./public/
        git add .
        git commit -F ../commit-message.log
        git push --force --quiet "https://${Coding_Username}:${Coding_Token}@${Coding_Pages}" master:master     


